"""Crear-tabla-municipios

Revision ID: 4c74a094b60e
Revises: a1bab4e67b55
Create Date: 2026-06-03 12:12:27.425165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4c74a094b60e'
down_revision: Union[str, Sequence[str], None] = 'a1bab4e67b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cvegeo', sa.String(length=10), nullable=False),
    sa.Column('cve_ent', sa.String(length=5), nullable=False),
    sa.Column('nomgeo', sa.String(length=100), nullable=False),
    sa.Column('cve_mun', sa.String(length=5), nullable=False),
    sa.Column('nommun', sa.String(length=150), nullable=False),
    sa.Column('cov', sa.Float(), nullable=True),
    sa.Column('cov_id', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_municipios_geom', 'municipios', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_municipios_cve_ent'), 'municipios', ['cve_ent'], unique=False)
    op.create_index(op.f('ix_municipios_cvegeo'), 'municipios', ['cvegeo'], unique=True)
    op.create_index(op.f('ix_municipios_nommun'), 'municipios', ['nommun'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_municipios_nommun'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_cvegeo'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_cve_ent'), table_name='municipios')
    # op.drop_index('idx_municipios_geom', table_name='municipios', postgresql_using='gist')
    op.drop_table('municipios')
    # ### end Alembic commands ###
