"""add is_active to region

Revision ID: 9eee75625bd6
Revises: 58ee2b532060
Create Date: 2026-05-26 14:56:45.003643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eee75625bd6'
down_revision: Union[str, Sequence[str], None] = '58ee2b532060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regiones', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regiones', 'is_active')
    # ### end Alembic commands ###
