"""indicador-macro

Revision ID: d64bb05bddd9
Revises: 4c74a094b60e
Create Date: 2026-06-04 18:52:58.899329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd64bb05bddd9'
down_revision: Union[str, Sequence[str], None] = '4c74a094b60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicadores_macro',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_indicador', sa.String(length=50), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('fecha_captura', sa.Date(), nullable=False),
    sa.Column('datos_vectoriales', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_indicador', 'entidad_tipo', 'entidad_id', 'fecha_captura', name='uix_indicador_entidad_fecha')
    )
    op.create_index(op.f('ix_indicadores_macro_entidad_id'), 'indicadores_macro', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_indicadores_macro_fecha_captura'), 'indicadores_macro', ['fecha_captura'], unique=False)
    op.create_index(op.f('ix_indicadores_macro_tipo_indicador'), 'indicadores_macro', ['tipo_indicador'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicadores_macro_tipo_indicador'), table_name='indicadores_macro')
    op.drop_index(op.f('ix_indicadores_macro_fecha_captura'), table_name='indicadores_macro')
    op.drop_index(op.f('ix_indicadores_macro_entidad_id'), table_name='indicadores_macro')
    op.drop_table('indicadores_macro')
    # ### end Alembic commands ###
