"""Crear-tabla-regiones

Revision ID: 58ee2b532060
Revises: 
Create Date: 2026-05-25 20:32:13.812500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '58ee2b532060'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_region', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),

    sa.Column('metadatos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_regiones_geom', 'regiones', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_regiones_nombre_region'), 'regiones', ['nombre_region'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regiones_nombre_region'), table_name='regiones')
    # op.drop_index('idx_regiones_geom', table_name='regiones', postgresql_using='gist')
    op.drop_table('regiones')
    # ### end Alembic commands ###
