"""create_ndvi_region_stats_table

Revision ID: a1bab4e67b55
Revises: 9eee75625bd6
Create Date: 2026-05-27 15:03:16.928753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1bab4e67b55'
down_revision: Union[str, Sequence[str], None] = '9eee75625bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ndvi_region_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('fecha_observacion', sa.Date(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=False),
    sa.Column('mediana', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.Column('histograma', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cobertura_nubes', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regiones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndvi_region_stats_fecha_observacion'), 'ndvi_region_stats', ['fecha_observacion'], unique=False)
    op.create_index(op.f('ix_ndvi_region_stats_id'), 'ndvi_region_stats', ['id'], unique=False)
    op.create_index(op.f('ix_ndvi_region_stats_region_id'), 'ndvi_region_stats', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ndvi_region_stats_region_id'), table_name='ndvi_region_stats')
    op.drop_index(op.f('ix_ndvi_region_stats_id'), table_name='ndvi_region_stats')
    op.drop_index(op.f('ix_ndvi_region_stats_fecha_observacion'), table_name='ndvi_region_stats')
    op.drop_table('ndvi_region_stats')
    # ### end Alembic commands ###
